name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: guefisa/labeler@master
        with:
          add-labels: "question"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
